app/app/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('admin/', admin.site.urls),
    path('ubicaciones/',include(('ubicaciones.urls','ubicaciones'), namespace='ubicaciones')),
    path('clientes/',include(('clientes.urls','clientes'), namespace='clientes')),
    path('telas/',include(('telas.urls','telas'), namespace='telas')),
    path('proveedores/',include(('proveedores.urls','proveedores'), namespace='proveedores')),
    path('compras/',include(('compras.urls','compras'), namespace='compras')),
    path('ventas/',include(('ventas.urls','ventas'), namespace='ventas')),
    path('tipos/',include(('tipos.urls','tipos'), namespace='tipos')),
    path('configuracion/',include(('configuracion.urls','configuracion'), namespace='configuracion')),
    path('cajas/',include(('cajas.urls','cajas'), namespace='cajas')),
    path('dashboard',include(('dashboard.urls','dashboard'), namespace='dashboard')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('users/',include(('user.urls','user'), namespace='user')),
]

app/proveedores/urls.py
from django.urls import path
from .views import ProveedorView, ProveedorCreate, ProveedorEdit, proveedor_delete, search_ruc

urlpatterns = [
    path('proveedores/',ProveedorView.as_view(), name='proveedor_list'),
    path('proveedores/create', ProveedorCreate.as_view(), name='proveedor_create'),
    path('proveedores/<int:pk>/edit', ProveedorEdit.as_view(), name='proveedor_edit'),
    path('proveedores/<int:id>/delete', proveedor_delete, name='proveedor_delete'),
    path('proveedores/search_ruc', search_ruc, name='search_ruc'),
]

app/proveedores/models.py
from django.db import models
from django.forms import model_to_dict
from bases.models import ClaseModelo
from ubicaciones.models import Ciudad

class Proveedor(ClaseModelo):
    ciudad = models.ForeignKey(Ciudad, models.PROTECT)

    nombre_empresa=models.CharField(
        max_length=100
    )
    direccion=models.CharField(
        max_length=250,
        null=True, blank=True
    )
    telefono=models.CharField(
        max_length=20,
        null=True, blank=True
    )
    email=models.CharField(
        max_length=250,
        null=True, blank=True
    )
    ruc=models.CharField(
        max_length=100,
        unique=True,
        error_messages={
            'unique': 'El campo Ruc ya existe'
        }
    )

    def __str__(self):
        return '{}'.format(self.nombre_empresa)
    
    def save(self):
        self.nombre_empresa=self.nombre_empresa.upper()
        super(Proveedor, self).save()

    def toJSON(self):
        item = model_to_dict(self)
        item['ciudad'] = self.ciudad.descripcion
        return item

    class Meta:
        verbose_name_plural = "Proveedores"

app/proveedores/forms.py
from django import forms

from .models import Proveedor
from ubicaciones.models import Ciudad

class ProveedorForm(forms.ModelForm):
    ciudad=forms.ModelChoiceField(
        queryset=Ciudad.objects.order_by('descripcion')
    )
    class Meta:
        model = Proveedor
        fields = [
            'ciudad',
            'nombre_empresa',
            'direccion',
            'telefono',
            'email',
            'ruc',
        ]
        labels = {
            'ciudad':'Ciudad',
            'nombre_empresa':'Nombre de la Empresa',
            'direccion':'Dirección',
            'telefono':'Teléfono/Celular',
            'email':'E-mail',
            'ruc':'Ruc',
		}
        widgets = {
            'ciudad' : forms.Select(attrs={'class':'form-control'}),
			'nombre_empresa' : forms.TextInput(attrs={'class':'form-control','autocomplete':'off'}),
			'direccion' : forms.TextInput(attrs={'class':'form-control','autocomplete':'off'}),
			'telefono' : forms.TextInput(attrs={'class':'form-control','autocomplete':'off'}),
            'email':forms.EmailInput(attrs={'class':'form-control','autocomplete':'off'}),
			'ruc' : forms.TextInput(attrs={'class':'form-control','autocomplete':'off'}),
		}

    '''def clean (self):
        try:
            proveedor = Proveedor.objects.get(
                ruc = self.cleaned_data["ruc"]
            )
            if not self.instance.pk:
                raise forms.ValidationError("Registro ya existe")
            elif self.instance.pk != proveedor.pk:
                raise forms.ValidationError("Cambio no permitido, ya existe este regristro")
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data'''

app/proveedores/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import ProtectedError
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from bases.mixins import ValidatePermissionRequired
from django.http import HttpResponse, JsonResponse, response
from datetime import datetime
from .models import Proveedor
from .forms import ProveedorForm
from ubicaciones.models import Ciudad


class ProveedorView(LoginRequiredMixin,ValidatePermissionRequired,generic.ListView):
    model = Proveedor 
    permission_requied = 'proveedores.view_proveedor'
    template_name = "proveedores/proveedor_list.html"
    login_url = 'bases:login'
    
    def queryset(self):
        proveedores = Proveedor.objects.filter(fecha_eliminacion__isnull=True)
        proveedor = self.request.POST['proveedor']
        if proveedor:
            proveedores = proveedores.filter(Q(nombre_empresa__icontains=proveedor) | Q(ruc__icontains=proveedor))
        return proveedores


    def post(self, request, *args, **kwargs):
        data={}
        try:
            if request.POST['action'] == 'search':
                data = []
                proveedores = self.queryset()
                for proveedor in proveedores:
                    data.append(proveedor.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'
        except Exception as e:
            print(e)
            data['error'] = str(e)
        
        return JsonResponse(data, safe=False)


class ProveedorCreate(LoginRequiredMixin,ValidatePermissionRequired, generic.CreateView):
    model=Proveedor
    permission_required = 'proveedores.add_proveedor'
    template_name="proveedores/proveedor_form.html"
    context_object_name="obj"
    form_class=ProveedorForm
    success_url=reverse_lazy("proveedores:proveedor_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_created = self.request.user
        form.instance.estado = True
        messages.success(self.request, 'Proveedor registrado éxitosamente.')
        return super().form_valid(form)


    def get_context_data (self, **kwargs):
        context = super(ProveedorCreate,self).get_context_data(**kwargs)
        context ["ciudades"] = Ciudad.objects.all()
        return context


class ProveedorEdit(LoginRequiredMixin,ValidatePermissionRequired, generic.UpdateView):
    model=Proveedor
    permission_required = 'proveedores.change_proveedor'
    template_name="proveedores/proveedor_form.html"
    context_object_name="obj"
    form_class=ProveedorForm
    success_url=reverse_lazy("proveedores:proveedor_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_updated = self.request.user.id
        messages.success(self.request, 'Proveedor modificado éxitosamente.')
        return super().form_valid(form)

    def get_context_data (self, **kwargs):
        pk = self.kwargs.get('pk')
        context = super(ProveedorEdit,self).get_context_data(**kwargs)
        context ["ciudades"] = Ciudad.objects.all()
        context ["obj"] = Proveedor.objects.filter(pk=pk).first()
        return context

def proveedor_delete(request,id):
    try:
        proveedor= Proveedor.objects.get(pk=id)
        proveedor.fecha_eliminacion = datetime.now()
        proveedor.save()
        data = {
            'error':False, 
            'message':"Registro eliminado correctamente."
        }
    except Proveedor.DoesNotExist:
        data = {
            'error':True, 
            'message':"No se encontro el registro."
        }
    return JsonResponse(data, safe=False)

def search_ruc(request):
    ruc = request.GET.get('ruc')
    proveedor = Proveedor.objects.get(ruc = ruc)
    print(proveedor)
    if proveedor:
        data = {
            'existe':True,
            'message':'El campo ruc ya existe'
        }
    else:
        data = {
            'existe':False,
            'message':''
        }
    return JsonResponse(data, safe=False)

app/templates/proveedores/proveedor_form.html
{% extends 'base/base.html' %}

{% block css %}
    <style>
        span.error{
            color: red; font-size: 0.8em;
        }
        .select2-error {
            border: 1px solid #dc3545 !important;
            border-radius: 4px;
        }
    </style>
{% endblock css %}

{% block content %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Crear Proveedor</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'proveedores:proveedor_list' %}">Proveedores</a></li>
                        <li class="breadcrumb-item active">Crear</li>
                    </ol>
                </div>               
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Datos del Proveedor</h3>
                        </div>
                        <div class="card-body">
                            {% if obj %}
                                <form method="POST" role="form" id="form" action="{% url 'proveedores:proveedor_edit' obj.pk %}">
                            {% else %}
                                <form method="POST" role="form" id="form" action="{% url 'proveedores:proveedor_create' %}">
                            {% endif %}
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-4" id="grupo_nombre_empresa">
                                        <div class="form-group">
                                            <label form="id_nombre_empresa"><strong>Nombre de la Empresa</strong></label>
                                                {{form.nombre_empresa}}
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group" id="grupo_ruc">
                                            <label form="id_ruc"><strong>{{form.ruc.label}}</strong></label>
                                                {{form.ruc}}
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">

                                            <label form="id_ciudad"><strong>{{form.ciudad.label}}</strong></label>
                                            <select class="form-control"  name = "ciudad" id="id_ciudad">
                                                {% for ciudad in ciudades %}
                                                    <option value="{{ ciudad.id }}">{{ ciudad.descripcion }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label form="id_direccion"><strong>{{form.direccion.label}}</strong></label>
                                                {{form.direccion}}
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group" id="grupo_telefono">
                                            <label form="id_telefono"><strong>{{form.telefono.label}}</strong></label>
                                                {{form.telefono}}
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group" id="grupo_email">
                                            <label form="id_email"><strong>{{form.email.label}}</strong></label>
                                                {{form.email}}
                                        </div>
                                    </div>
                                </div>
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col">
                                        <button type="submit" class="btn btn-primary"><span class="fa fa-save"></span> Guardar</button>
                                        <a class="btn btn-danger float-right" href="{% url 'proveedores:proveedor_list' %}">Cancelar</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js_page %}
<script>
    $(document).ready(function(){
        $('#id_ciudad').val("{{ obj.ciudad.id }}").change();
        $('#id_ciudad').select2({
            width: '100%'
        });

        $('#id_ciudad').on('change', function () {
            $(this).valid();
        });

        $("#form").validate({
		    rules: {
		    	nombre_empresa: {required: true, empresaRule:true},
		    	ruc: {required: true, rucRule:true},
                ciudad: {required: true},
		    	telefono: {required: false, telRule:true},
                email: {required: false, email: true ,emailRule:true},
            },
            messages: {
                nombre_empresa : {required: "* El campo es requerido"},
                ruc : {required: "* El campo es requerido"},
                ciudad : {required: "* Debe seleccionar una ciudad"},
                email : {email: "* Ingrese un correo válido. Ej: example@gmail.com"},
            },
            errorElement: 'span',
            highlight: function(element){
                if (element.name == 'nombre_empresa' || element.name == 'ruc') {
                    $(element).closest('.form-control').addClass('is-invalid');
                    $(element).closest('.form-control').removeClass('is-valid');
                }
            },
            unhighlight: function(element){
                if (element.name == 'nombre_empresa' || element.name == 'ruc') {
                    $(element).addClass('is-valid');
                    $(element).closest('.form-control').removeClass('is-invalid');
                }
            },
            errorPlacement: function (error, element) {
                if(element.hasClass("select2-hidden-accessible")) {
                    $(element).closest('.form-control').addClass('select2-error');
                    error.insertAfter(element.next('span'));
                } else {
                    error.insertAfter(element);
                }
            },
            /*submitHandler: function(form){
                $.ajax({
                    url: 'search_ruc',
                    type: 'GET',
                    data: {
                        'ruc' : $('#id_ruc').val()
                    },
                    success: function(response) {
                        if (response.existe){
                            var element = document.getElementById("id_ruc");
                            element.classList.add('is-invalid');
                            document.getElementById("ruc_duplicate").setAttribute('style','display:block;color:red');
                        }
                    }            
                });
                return false;		
            }*/
        });

        $.validator.addMethod("empresaRule", function (value, element) {
            var pattern = /^[a-zA-Z.-\s]+$/i;
            return this.optional(element) || pattern.test(value);
        }, "* El campo debe tener letras");

        $.validator.addMethod("rucRule", function (value, element) {
            var pattern = /^[0-9]+(?:-[0-9])$/;
            return this.optional(element) || pattern.test(value);
        }, "* El formato del ruc debe ser: 123456-0");

        $.validator.addMethod("telRule", function (value, element) {
            var pattern = /^[0-9]+$/;
            return this.optional(element) || pattern.test(value);
        }, "* El formato del telefono debe ser: 0987654321. 646713");

        $.validator.addMethod("emailRule", function (value, element) {
            var pattern = /^([a-zA-Z0-9_.-])+@([a-zA-Z0-9_.-])+\.([a-zA-Z])+([a-zA-Z])+/;
            return this.optional(element) || pattern.test(value);
        }, "* Formato del correo incorrecto. Ej: example@gmail.com");
    
    });
</script>
{% endblock js_page %}

app/templates/proveedores/proveedor_list.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Proveedores</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item active">Proveedores</li>
                    </ol>
                </div>               
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Listado de Proveedores</h3>
                        </div>
                        <div class="card-body">
                            <div class="row justify-content-end">
                                <div class="col-md-2">
                                    <a href="{% url 'proveedores:proveedor_create' %}" class="btn btn-primary btn-block">
                                        <i class="fas fa-plus-square"></i> Nuevo Proveedor
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="proveedor"><strong>Proveedores:</strong></label>
                                    <input type="text" class="form-control" id="proveedor" placeholder="Buscar por Nombre de la Empresa, Ruc">
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <th>Empresa</th>
                                            <th>Ruc</th>
                                            <th>Ciudad</th>
                                            <th>Teléfono/Celular</th>
                                            <th class="all">Acciones</th>
                                        </thead>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js_page %}
    {% include 'base/partials/sweet_delete.html' %}
    <script>
        $(document).ready(function() {           
            var table = $('.table').DataTable({
                responsive: true,
                autoWidth: false,
                filter: false,
                ajax: {
                    headers: { "X-CSRFToken": '{{csrf_token}}' },
                    url: window.location.pathname,
                    type: 'POST',
                    "data": function (d) {
                        d.action = 'search',
                        d.proveedor = $('#proveedor').val()
                    },
                    dataSrc: ""
                },
                columns: [
                    { "data": "nombre_empresa"},
                    { "data": "ruc"},
                    { "data": "ciudad"},
                    { "data": "telefono"},
                    { 
                        "render": function( data, type, full ) {
                            return '<a class="btn btn-warning btn-circle btn-sm" title="Editar" href="/proveedores/proveedores/'+ full.id+'/edit"> <i class="fas fa-edit"></i> </a>' + 
                                    ' <button class="btn btn-danger btn-circle btn-sm" onclick="eliminar(\'/proveedores/proveedores/'+full.id+'/delete\',\'/proveedores/proveedores\')"><i class="fa fa-trash"></i></button>';
                        },
                        "orderable":false
                    }
                ],
                language:{
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "processing": '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> ',
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "{Filtrando de _MAX_ total de entradas}",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encotrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior",
                    }
                }
            });
            $('#proveedor').keyup(function(){
                table.ajax.reload();
            });
        });
    </script>
{% endblock js_page %}