app/app/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('admin/', admin.site.urls),
    path('ubicaciones/',include(('ubicaciones.urls','ubicaciones'), namespace='ubicaciones')),
    path('clientes/',include(('clientes.urls','clientes'), namespace='clientes')),
    path('telas/',include(('telas.urls','telas'), namespace='telas')),
    path('proveedores/',include(('proveedores.urls','proveedores'), namespace='proveedores')),
    path('compras/',include(('compras.urls','compras'), namespace='compras')),
    path('ventas/',include(('ventas.urls','ventas'), namespace='ventas')),
    path('tipos/',include(('tipos.urls','tipos'), namespace='tipos')),
    path('configuracion/',include(('configuracion.urls','configuracion'), namespace='configuracion')),
    path('cajas/',include(('cajas.urls','cajas'), namespace='cajas')),
    path('dashboard',include(('dashboard.urls','dashboard'), namespace='dashboard')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('users/',include(('user.urls','user'), namespace='user')),
]

app/configuracion/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    #rutas para Usuario
    path('configuracion/',ConfiguracionUsuarioView.as_view(), name='configuracion_usuario_list'),
    path('configuracion/<int:pk>/edit', ConfiguracionUsuarioEdit.as_view(), name='configuracion_usuario_edit'),

    #rutas para Producto
    path('configuracion_producto/',ConfiguracionProductoView.as_view(), name='configuracion_producto_list'),
    path('configuracion_producto/<int:pk>/edit', ConfiguracionProductoEdit.as_view(), name='configuracion_producto_edit'),

    #rutas para Venta
    path('configuracion_venta/',ConfiguracionVentaView.as_view(), name='configuracion_venta_list'),
    path('configuracion_venta/create',ConfiguracionVentaCreate.as_view(), name='configuracion_venta_create'),
    path('configuracion_venta/<int:pk>/edit', ConfiguracionVentaEdit.as_view(), name='configuracion_venta_edit'),

    #rutas para Egreso
    path('configuracion_egreso/',ConfiguracionEgresoView.as_view(), name='configuracion_egreso_list'),
    path('configuracion_egreso/<int:pk>/edit', ConfiguracionEgresoEdit.as_view(), name='configuracion_egreso_edit'),
]

app/configuracion/models.py
from django.db import models
from bases.models import ClaseModelo

class ConfiguracionUsuario(ClaseModelo):
    metraje_minimo = models.FloatField(unique=True,
                                        error_messages={
                                            'unique': 'Metraje minimo ya existente'
                                        })

    class Meta:
        verbose_name_plural ="Configuracion Usuario"

class ConfiguracionProducto(ClaseModelo):
    descripcion = models.CharField(max_length=200)
    porcentaje = models.FloatField()

    class Meta:
        verbose_name_plural ="Configuracion de Producto"


class ConfiguracionVenta(ClaseModelo):
    rubro = models.IntegerField()
    sucursal = models.IntegerField()
    numero = models.IntegerField()
    timbrado = models.IntegerField()
    fecha_inicio_timbrado = models.DateField()
    fecha_fin_timbrado = models.DateField()


    class Meta:
        verbose_name_plural ="Configuracion de Venta"

class ConfiguracionEgreso(ClaseModelo):
    monto_maximo = models.IntegerField(unique=True,
                                        error_messages={
                                            'unique': 'Monto Máximo ya existente'
                                        })

    class Meta:
        verbose_name_plural ="Configuracion Egreso"

app/configuracion/forms.py
from django import forms
from datetime import datetime
from .models import ConfiguracionUsuario, ConfiguracionProducto, ConfiguracionVenta, ConfiguracionEgreso


class ConfiguracionUsuarioForm(forms.ModelForm):
    class Meta:
        model = ConfiguracionUsuario
        fields = [
            'metraje_minimo'
        ]
        labels = {
            'metraje_minimo':"Metraje Minimo:"
        }
        widgets = {
            'metraje_minimo':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required'}),
        }

class ConfiguracionProductoForm(forms.ModelForm):
    class Meta:
        model = ConfiguracionProducto
        fields = [
            'descripcion',
            'porcentaje'
        ]
        labels = {
            'descripcion':"Descripcion:",
            'porcentaje':"Porcentaje:"
        }
        widgets = {
            'descripcion':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required'}),
            'porcentaje':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required'}),
        }

class ConfiguracionVentaForm(forms.ModelForm):
    class Meta:
        model = ConfiguracionVenta
        fields = [
            'rubro',
            'sucursal',
            'numero',
            'timbrado',
            'fecha_inicio_timbrado',
            'fecha_fin_timbrado'
        ]
        labels = {
            'rubro':"Rubro:",
            'sucursal':"Sucursal:",
            'numero':"Numero:",
            'timbrado':"Timbrado:",
            'fecha_inicio_timbrado':"Fecha Inicio Timbrado:",
            'fecha_fin_timbrado':"Fecha Fin Timbrado:"
        }
        widgets = {
            'rubro':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required','min':'1','max':'9'}),
            'sucursal':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required','min':'1','max':'9'}),
            'numero':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required', 'range':[1,9999999]}),
            'timbrado':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required'}),
            'fecha_inicio_timbrado': forms.DateInput(
                format='%d-%m-%Y',
                attrs={
                    'value': datetime.now().strftime('%d/%m/%Y'),
                    'autocomplete': 'off',
                    'class': 'form-control datetimepicker-input',
                    'id': 'fecha_inicio_timbrado',
                    'data-target': '#fecha_inicio_timbrado',
                    'onkeydown':'return false',
                    'data-toggle': 'datetimepicker'
                }
            ),
            'fecha_fin_timbrado': forms.DateInput(
                format='%d-%m-%Y',
                attrs={
                    'value': datetime.now().strftime('%d/%m/%Y'),
                    'autocomplete': 'off',
                    'class': 'form-control datetimepicker-input',
                    'id': 'fecha_fin_timbrado',
                    'data-target': '#fecha_fin_timbrado',
                    'onkeydown':'return false',
                    'data-toggle': 'datetimepicker'
                }
            ),
        }

class ConfiguracionEgresoForm(forms.ModelForm):
    class Meta:
        model = ConfiguracionEgreso
        fields = [
            'monto_maximo'
        ]
        labels = {
            'monto_maximo':"Monto Máximo:"
        }
        widgets = {
            'monto_maximo':forms.TextInput(attrs={'class':'form-control','autocomplete':'off', 'required':'required'}),
        }

app/configuracion/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from bases.mixins import ValidatePermissionRequired
from .models import  ConfiguracionUsuario, ConfiguracionProducto, ConfiguracionVenta, ConfiguracionEgreso
from .forms import ConfiguracionUsuarioForm, ConfiguracionProductoForm, ConfiguracionVentaForm, ConfiguracionEgresoForm
from datetime import datetime, date

class ConfiguracionUsuarioView(LoginRequiredMixin,ValidatePermissionRequired, generic.ListView):
    paginate_by = 6
    permission_required = 'configuracion.view_configuracionusuario'
    template_name = "configuracion/configuracion_usuario_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

    def get_queryset(self):
        queryset = ConfiguracionUsuario.objects.filter(fecha_eliminacion__isnull=True)
        return queryset

class ConfiguracionUsuarioEdit(LoginRequiredMixin,ValidatePermissionRequired, generic.UpdateView):
    model=ConfiguracionUsuario
    permission_required = 'configuracion.change_configuracionusuario'
    template_name="configuracion/configuracion_usuario_form.html"
    context_object_name = 'obj'
    form_class=ConfiguracionUsuarioForm
    success_url= reverse_lazy("configuracion:configuracion_usuario_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_updated_id = self.request.user.id 
        messages.success(self.request, 'Registro actualizado correctamente')
        return super().form_valid(form)

class ConfiguracionProductoView(LoginRequiredMixin,ValidatePermissionRequired, generic.ListView):
    paginate_by = 6
    permission_required = 'configuracion.view_configuracionproducto'
    template_name = "configuracion/configuracion_producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

    def get_queryset(self):
        queryset = ConfiguracionProducto.objects.filter(fecha_eliminacion__isnull=True)
        return queryset

class ConfiguracionProductoEdit(LoginRequiredMixin,ValidatePermissionRequired, generic.UpdateView):
    model=ConfiguracionProducto
    permission_required = 'configuracion.change_configuracionproducto'
    template_name="configuracion/configuracion_producto_form.html"
    context_object_name = 'obj'
    form_class=ConfiguracionProductoForm
    success_url= reverse_lazy("configuracion:configuracion_producto_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_updated_id = self.request.user.id 
        messages.success(self.request, 'Registro actualizado correctamente')
        return super().form_valid(form)
    

class ConfiguracionVentaView(LoginRequiredMixin, ValidatePermissionRequired,generic.ListView):
    paginate_by = 6
    permission_required = 'configuracion.view_configuracionventa'
    template_name = "configuracion/configuracion_venta_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["fecha_hoy"] = datetime.now().strftime('%Y-%m-%d')
        return context
    

    def get_queryset(self):
        queryset = ConfiguracionVenta.objects.filter(fecha_eliminacion__isnull=True)
        return queryset

class ConfiguracionVentaCreate(LoginRequiredMixin,ValidatePermissionRequired, generic.CreateView):
    model = ConfiguracionVenta
    permission_required = 'configuracion.add_configuracionventa'
    template_name="configuracion/configuracion_venta_form.html"
    context_object_name = 'obj'
    form_class=ConfiguracionVentaForm
    success_url= reverse_lazy("configuracion:configuracion_venta_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_created = self.request.user
        form.instance.estado = True
        messages.success(self.request, 'Registro actualizado correctamente')
        return super().form_valid(form)

class ConfiguracionVentaEdit(LoginRequiredMixin,ValidatePermissionRequired, generic.UpdateView):
    model=ConfiguracionVenta
    permission_required = 'configuracion.change_configuracionventa'
    template_name="configuracion/configuracion_venta_form.html"
    context_object_name = 'obj'
    form_class=ConfiguracionVentaForm
    success_url= reverse_lazy("configuracion:configuracion_venta_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_updated_id = self.request.user.id 
        messages.success(self.request, 'Registro actualizado correctamente')
        return super().form_valid(form)

class ConfiguracionEgresoView(LoginRequiredMixin,ValidatePermissionRequired, generic.ListView):
    paginate_by = 6
    permission_required = 'configuracion.view_configuracionegreso'
    template_name = "configuracion/configuracion_egreso_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

    def get_queryset(self):
        queryset = ConfiguracionEgreso.objects.filter(fecha_eliminacion__isnull=True)
        return queryset

class ConfiguracionEgresoEdit(LoginRequiredMixin,ValidatePermissionRequired, generic.UpdateView):
    model=ConfiguracionEgreso
    permission_required = 'configuracion.change_configuracionegreso'
    template_name="configuracion/configuracion_egreso_form.html"
    context_object_name = 'obj'
    form_class=ConfiguracionEgresoForm
    success_url= reverse_lazy("configuracion:configuracion_egreso_list")
    login_url="bases:login"

    def form_valid(self, form):
        form.instance.user_updated_id = self.request.user.id 
        messages.success(self.request, 'Registro actualizado correctamente')
        return super().form_valid(form)

app/templates/configuracion/configuracion_egreso_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Crear Cantidad Máxima Egreso</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'configuracion:configuracion_egreso_list' %}">Egreso Máximo</a></li>
                        <li class="breadcrumb-item active">Crear</li>
                    </ol>
                </div>               
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Datos del Egreso Máximo</h3>
                        </div>
                    
                        <div class="card-body">
                            {% if obj %}
                                <form method="POST" role="form" id="form" action="{% url 'configuracion:configuracion_egreso_edit' obj.pk %}">
                            {% else %}
                                <form method="POST" role="form" id="form" action="{% url 'configuracion:configuracion_egreso_create' %}">
                            {% endif %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_monto_maximo"><strong>{{form.monto_maximo.label}}</strong></label>
                                    {{form.monto_maximo}}
                                </div>
                            </div>
                            <br>
                            <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Guardar</button>
                                            
                                            <a class="btn btn-danger float-right" href="{% url 'configuracion:configuracion_egreso_list' %}">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js_page %}
<script>
 $(document).ready(function(){
    var monto_maximo = document.getElementById("id_monto_maximo");
    monto_maximo.addEventListener('keyup', function(evt){
        var n = this.value.replace(/\D/g,"")//Reemplaza los no digitos, ej: A, ?, _
                          .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, "."); //
        monto_maximo.value = n;
    }, false);

    $("#form").validate({
        rules: {
            monto_maximo: {required: true, montoRule:true},
            descripcion: {required: false},
        },
        messages: {
            monto_maximo: {required: "* El campo es requerido"},
        },
        errorElement: 'span',
        highlight: function(element){
            if (element.name == 'monto_maximo') {
                $(element).closest('.form-control').addClass('is-invalid');
                $(element).closest('.form-control').removeClass('is-valid');
            }
        },
        unhighlight: function(element){
            if (element.name == 'monto_maximo') {
                $(element).closest('.form-control').addClass('is-valid');
                $(element).closest('.form-control').removeClass('is-invalid');
            }
        }
    });

    $.validator.addMethod("montoRule", function (value, element) {
            value = value.split('.').join('');
            return parseInt(value) > 0
        }, "* El campo debe ser mayor a 0");

    $(form).on('submit', function (e){
        var monto_maximo = String($('#id_monto_maximo').val());
        monto_maximo = monto_maximo.split('.').join(''); 
        $('#id_monto_maximo').val(monto_maximo);
    });            
 });
</script>
{% endblock js_page %}

app/templates/configuracion/configuracion_producto_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Crear IVA</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'configuracion:configuracion_producto_list' %}">IVA's</a></li>
                        <li class="breadcrumb-item active">Crear</li>
                    </ol>
                </div>               
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Datos del Iva</h3>
                        </div>
                    
                        <div class="card-body">
                            {% if obj %}
                                <form method="POST" role="form" id="form" action="{% url 'configuracion:configuracion_producto_edit' obj.pk %}">
                            {% else %}
                                <form method="POST" role="form" id="form" action="{% url 'configuracion:configuracion_producto_create' %}">
                            {% endif %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_descripcion"><strong>{{form.descripcion.label}}</strong></label>
                                    {{form.descripcion}}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_porcentaje"><strong>{{form.porcentaje.label}}</strong></label>
                                    {{form.porcentaje}}
                                </div>
                            </div>
                            <br>
                            <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Guardar</button>
                                            
                                            <a class="btn btn-danger float-right" href="{% url 'configuracion:configuracion_producto_list' %}">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js_page %}
<script>
 $(document).ready(function(){
     var porcentaje = document.getElementById("id_porcentaje");
    porcentaje.addEventListener('keyup', function(evt){
        var n = this.value.replace(/\D/g, "") //Reemplaza los no digitos por espacio en cada ocurrencia
                          .replace(/([0-9])([0-9]{2})$/, '$1.$2')  
        porcentaje.value = n;
    }, false);

    $("#form").validate({
        rules: {
            descripcion: {required: true, nombreRule:true},
            porcentaje: {required: true},
        },
        messages: {
            descripcion: {required: "* El campo es requerido"},
            porcentaje: {required: "* El campo es requerido"},
        },
        errorElement: 'span',
        highlight: function(element){
            console.log(element);
            if (element.name == 'porcentaje' || element.name == 'descripcion') {
                $(element).closest('.form-control').addClass('is-invalid');
                $(element).closest('.form-control').removeClass('is-valid');
            }
        },
        unhighlight: function(element){
            console.log(element);

            if (element.name == 'porcentaje' || element.name == 'descripcion') {
                $(element).addClass('is-valid');
                $(element).closest('.form-control').removeClass('is-invalid');
            }
        }
    });

    $.validator.addMethod("nombreRule", function (value, element) {
            var pattern = /^[a-zA-Z.-%\s]+$/i;
            return this.optional(element) || pattern.test(value);
        }, "* El campo debe tener letras");

     $(form).on('submit', function (e){
        var porcentaje = String($('#id_porcentaje').val());
        porcentaje = porcentaje.replace('.','')
                         .replace(',','.');
        $('#id_porcentaje').val(metraje_minimo);

    });
 });
</script>
{% endblock js_page %}

app/templates/configuracion/configuracion_venta_form.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Crear configuracion Factura </h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/"><i class="fas fa-home"></i> Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'configuracion:configuracion_venta_list' %}">Configuraciones</a></li>
                        <li class="breadcrumb-item active">Crear</li>
                    </ol>
                </div>               
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-secondary">
                        <div class="card-header">
                            <h3 class="card-title">Datos de la Configuracion de la Factura</h3>
                        </div>
                    
                        <div class="card-body">
                            {% if obj %}
                                <form method="POST" role="form" id="form" action="{% url 'configuracion:configuracion_venta_edit' obj.pk %}">
                            {% else %}
                                <form method="POST" role="form" id="form" action="{% url 'configuracion:configuracion_venta_create' %}">
                            {% endif %}
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_rubro"><strong>{{form.rubro.label}}</strong></label>
                                    {{form.rubro}}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_sucursal"><strong>{{form.sucursal.label}}</strong></label>
                                    {{form.sucursal}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_numero"><strong>{{form.numero.label}}</strong></label>
                                    {{form.numero}}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_timbrado"><strong>{{form.timbrado.label}}</strong></label>
                                    {{form.timbrado}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="id_fecha_inicio_timbrado"><strong>{{form.fecha_inicio_timbrado.label}}</strong></label>
                                    {{form.fecha_inicio_timbrado}}
                                </div>
                                <div class="col-md-6">
                                    <label for="id_fecha_fin_timbrado"><strong>{{form.fecha_fin_timbrado.label}}</strong></label>
                                    {{form.fecha_fin_timbrado}}
                                </div>
                            </div>
                            <br>
                            <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Guardar</button>
                                            
                                            <a class="btn btn-danger float-right" href="{% url 'configuracion:configuracion_venta_list' %}">Cancelar</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js_page %}
<script>
$(document).ready(function(){
    $('#fecha_inicio_timbrado').datetimepicker({
        format: 'DD/MM/YYYY',
        locale: 'es',
        //maxDate: moment($('#fecha_fin_timbrado').val()).format("DD/MM/YYYY")
    });

    $('#fecha_fin_timbrado').datetimepicker({
        format: 'DD/MM/YYYY',
        locale: 'es',
        //minDate: moment($('#fecha_inicio_timbrado').val()).format("DD/MM/YYYY")
    });
    
    $.extend( $.validator.messages, {
        min: $.validator.format("Por favor ingrese un valor mayor a 0"),
        max: $.validator.format("Por favor ingrese solo un digito"),
        range: $.validator.format("Por favor ingrese un numero entre 1 y 9999999")

    });

    $("#form").validate({
        rules: {
            rubro: {required: true, numRule:true},
            sucursal: {required: true, numRule:true},
            numero: {required: true, numRule:true},
            timbrado: {required: true, numRule:true},
        },
        messages: {
            rubro : {required: "* El campo es requerido"},
            sucursal : {required: "* El campo es requerido"},
            numero : {required: "* El campo es requerido"},
            timbrado : {required: "* El campo es requerido"},
        },
        errorElement: 'span',
        highlight: function(element){
            console.log(element);
            if (element.name == 'rubro' || element.name == 'sucursal' || element.name == 'numero' || element.name == 'timbrado') {
                $(element).closest('.form-control').addClass('is-invalid');
                $(element).closest('.form-control').removeClass('is-valid');
            }
        },
        unhighlight: function(element){
            console.log(element);

            if (element.name == 'rubro' || element.name == 'sucursal' || element.name == 'numero' || element.name == 'timbrado') {
                $(element).addClass('is-valid');
                $(element).closest('.form-control').removeClass('is-invalid');
            }
        }
    });

    $.validator.addMethod("numRule", function (value, element) {
        var pattern = /^[0-9]+$/;
        return this.optional(element) || pattern.test(value);
    }, "* El campo debe ser numerico");

 });
</script>
{% endblock js_page %}