app/app/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('admin/', admin.site.urls),
    path('ubicaciones/',include(('ubicaciones.urls','ubicaciones'), namespace='ubicaciones')),
    path('clientes/',include(('clientes.urls','clientes'), namespace='clientes')),
    path('telas/',include(('telas.urls','telas'), namespace='telas')),
    path('proveedores/',include(('proveedores.urls','proveedores'), namespace='proveedores')),
    path('compras/',include(('compras.urls','compras'), namespace='compras')),
    path('ventas/',include(('ventas.urls','ventas'), namespace='ventas')),
    path('tipos/',include(('tipos.urls','tipos'), namespace='tipos')),
    path('configuracion/',include(('configuracion.urls','configuracion'), namespace='configuracion')),
    path('cajas/',include(('cajas.urls','cajas'), namespace='cajas')),
    path('dashboard',include(('dashboard.urls','dashboard'), namespace='dashboard')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('users/',include(('user.urls','user'), namespace='user')),
]

app/bases/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from bases.views import Home, LoginFormView

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', LoginFormView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'),
        name='logout'),
]

app/ventas/urls.py
from django.urls import path
from .views import VentaView, VentaCreate, VentaListadoPdfView, VentaEdit, VentaCobro

urlpatterns = [
    path('ventas/',VentaView.as_view(), name='ventas_list'),
    path('cobro_deuda/',VentaCobro.as_view(), name='ventas_cobro_list'),
    path('ventas/listado/pdf/<int:pk>/', VentaListadoPdfView.as_view(), name='ventas_listado_pdf'),
    path('ventas/create', VentaCreate.as_view(), name='venta_create'),
    path('ventas/<int:pk>/edit/', VentaEdit.as_view(), name='venta_edit'),

]

app/bases/models.py
from django.db import models
from user.models import User
#from django.contrib.auth.models import User

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    fecha_eliminacion = models.DateField(blank=True, null=True)
    user_created = models.ForeignKey(User, on_delete=models.PROTECT)
    user_updated_id = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract=True

app/bases/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.views import generic
from datetime import datetime
from telas.models import Tela
from ventas.models import Venta, CuotaVenta
from compras.models import Compra
from django.db.models import Sum, Count
from django.db.models.functions import Coalesce

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        stock_disponible = Tela.objects.filter(fecha_eliminacion__isnull=True).count()
        
        today = datetime.now()
        year = today.year
        month = today.month

        if (month == 1) :
            past_month = 12
            past_year = year - 1
        else:
            past_month = today.month - 1
            past_year = year

        venta_mes_anterior = Venta.objects.filter(fecha_venta__year=past_year, fecha_venta__month = past_month).aggregate(
                    r=Coalesce(Sum('monto_total'), 0)).get('r')

        venta_mes_actual = Venta.objects.filter(fecha_venta__year=year, fecha_venta__month = month).aggregate(
                    r=Coalesce(Sum('monto_total'), 0)).get('r')

        compra_mes_anterior = Compra.objects.filter(fecha_compra__year=past_year, fecha_compra__month = past_month).aggregate(
                    r=Coalesce(Sum('monto_total'), 0)).get('r')

        compra_mes_actual = Compra.objects.filter(fecha_compra__year=year, fecha_compra__month = month).aggregate(
                    r=Coalesce(Sum('monto_total'), 0)).get('r')

        if (venta_mes_anterior <= 0 and venta_mes_actual <= 0):
            nivel_venta = 0.00
        elif (venta_mes_anterior > 0 and venta_mes_actual <= 0):
            porcentaje_venta = ( int(venta_mes_anterior) /  -100 )
            nivel_venta = round (porcentaje_venta, 2)
        elif (venta_mes_anterior <= 0 and venta_mes_actual > 0):
            porcentaje_venta = ( int(venta_mes_actual) / 100) 
            nivel_venta = round (porcentaje_venta, 2)
        else:
            porcentaje_venta = ( int(venta_mes_actual) - int(venta_mes_anterior) ) / int(venta_mes_anterior) * 100
            nivel_venta = round (porcentaje_venta, 2)

        if (compra_mes_anterior <= 0 and compra_mes_actual <= 0):
            nivel_compra = 0.00
        elif (compra_mes_anterior > 0 and compra_mes_actual <= 0):
            porcentaje_compra = ( int(compra_mes_anterior) /  -100 )
            nivel_compra = round (porcentaje_compra, 2)
        elif (compra_mes_anterior <= 0 and compra_mes_actual > 0):
            porcentaje_compra = ( int(compra_mes_actual) / 100 ) 
            nivel_compra = round (porcentaje_compra, 2)
        else:
            porcentaje_compra = ( int(compra_mes_actual) - int(compra_mes_anterior) ) / int(compra_mes_anterior) * 100
            nivel_compra = round (porcentaje_compra, 2)

        clientes_adeudores = Venta.objects.filter(cuotaventa__estado=False,
                            cuotaventa__fecha_vencimiento__year=year, 
                            cuotaventa__fecha_vencimiento__month = month).annotate(
                                dcount=Count('cliente_id')
                            ).count()
        

        context["stock_disponible"] = stock_disponible
        context["venta_mes_actual"] = venta_mes_actual
        context["compra_mes_actual"] = compra_mes_actual
        context["nivel_venta"] = nivel_venta
        context["nivel_compra"] = nivel_compra
        context["clientes_adeudores"] = clientes_adeudores
        return context
    


class LoginFormView(LoginView):
    template_name = 'bases/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('bases:home')
        return super().dispatch(request, *args, **kwargs)

app/bases/templates/bases/home.html
{% extends 'base/base.html' %}


{% block content %}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0"> <i class="fas fa-door-open"></i> Bienvenido {{ request.user.first_name }} {{ request.user.last_name }} </h1>
                </div>               
            </div>
        </div>
    </div>

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box">
                        <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-tag"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text">Stock Disponible</span>
                            <span class="info-box-number">
                                {{ stock_disponible }} tela(s)
                            </span><br>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box mb-3">
                        <span class="info-box-icon bg-info elevation-1"><i class="fas fa-shopping-bag"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text">Compras Hechas</span>
                            <span class="info-box-number">Gs. {% load humanize  %} {{ compra_mes_actual|intcomma  }}<br>
                                {% if nivel_compra < 0 %}
                                    <span class="description-percentage text-danger"><i class="fas fa-caret-down"></i> {% load humanize  %} {{ nivel_compra|intcomma  }}%</span>
                                {% elif nivel_compra == 0 %}
                                    <span class="description-percentage text-warning"><i class="fas fa-caret-left"></i> {% load humanize  %} {{ nivel_compra|intcomma  }}%</span>
                                {% else %}
                                    <span class="description-percentage text-success"><i class="fas fa-caret-up"></i> {% load humanize  %} {{ nivel_compra|intcomma  }}%</span>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>

                <div class="clearfix hidden-md-up">
                </div>

                <div class="col-12 col-sm-6 col-md-3">
                    <div class="info-box mb-3">
                        <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">Ventas Realizadas</span>
                            <span class="info-box-number">Gs. {% load humanize  %} {{ venta_mes_actual|intcomma  }}<br>
                                {% if nivel_venta < 0 %}
                                    <span class="description-percentage text-danger"><i class="fas fa-caret-down"></i> {% load humanize  %} {{ nivel_venta|intcomma  }}%</span>
                                {% elif nivel_venta == 0 %}
                                    <span class="description-percentage text-warning"><i class="fas fa-caret-left"></i> {% load humanize  %} {{ nivel_venta|intcomma  }}%</span>
                                {% else %}
                                    <span class="description-percentage text-success"><i class="fas fa-caret-up"></i> {% load humanize  %} {{ nivel_venta|intcomma  }}%</span>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
                
                <div class="col-12 col-sm-6 col-md-3">
                    <a href="{% url 'ventas:ventas_cobro_list' %}" target="_blank">
                        <div class="info-box mb-3">
                            <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-chalkboard-teacher"></i></span>

                            <div class="info-box-content">
                                <span class="info-box-text">Clientes Adeudores</span>
                                <span class="info-box-number">{{ clientes_adeudores }}</span><br>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock content%}

app/bases/templates/bases/login.html
{% extends 'base/base.html' %}

{% load static%}
{% block css %}
    <style>
        .img-background{
            background-image: url( "{% static 'base/img/login.jpeg' %}");
        }
    </style>
{% endblock css %}

{% block body %}
    <body class="hold-transition login-page img-background">
        {% block side_bar %} {% endblock %}
        {% block content %} {% endblock %}
        {% block footer%} {% endblock %}
        {% block login %} 
            <div class="login-box">
                <!-- /.login-logo -->
                <div class="card card-outline card-primary">
                    <div class="card-header text-center">
                        <h1><b>Bienvenido</b></h1>
                    </div>
                    
                    <div class="card-body">
                        <p class="login-box-msg">Inicie su Sesión</p>

                        <form class="user" method="POST" id="form">
                            {% csrf_token %}
                            {{ form.non_field_errors }}
                            <div class="input-group mb-3">
                                <input type="text" class="form-control" id="id_username" name="username" placeholder="Usuario" autocomplete="off">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            {{ form.username.errors }}
                            <div class="input-group mb-3">
                                <input type="password" class="form-control" id="id_password" name="password" placeholder="Password">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-lock"></span>
                                    </div>
                                </div>
                            </div>
                            {{ form.password.errors }}
                            <div class="row">
                                <div class="col-lg-12">
                                    <button type="submit" class="btn btn-primary btn-block">
                                        <i class="fas fa-sign-in-alt"></i> Iniciar Sesión
                                    </button>
                                </div>
                                <!-- /.col -->
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.login-box -->    
        {% endblock %}  
    </body>
{% endblock body %}