app/app/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('admin/', admin.site.urls),
    path('ubicaciones/',include(('ubicaciones.urls','ubicaciones'), namespace='ubicaciones')),
    path('clientes/',include(('clientes.urls','clientes'), namespace='clientes')),
    path('telas/',include(('telas.urls','telas'), namespace='telas')),
    path('proveedores/',include(('proveedores.urls','proveedores'), namespace='proveedores')),
    path('compras/',include(('compras.urls','compras'), namespace='compras')),
    path('ventas/',include(('ventas.urls','ventas'), namespace='ventas')),
    path('tipos/',include(('tipos.urls','tipos'), namespace='tipos')),
    path('configuracion/',include(('configuracion.urls','configuracion'), namespace='configuracion')),
    path('cajas/',include(('cajas.urls','cajas'), namespace='cajas')),
    path('dashboard',include(('dashboard.urls','dashboard'), namespace='dashboard')),
    path('inventario/',include(('inventario.urls','inventario'), namespace='inventario')),
    path('users/',include(('user.urls','user'), namespace='user')),
]

app/cajas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('cajas/',CajaList.as_view(), name='caja_list'),
    path('cajas/create', CajaCreate.as_view(), name='caja_create'),
    path('cajas/listado/pdf/<int:pk>/', CajaListadoPdfView.as_view(), name='cajas_listado_pdf'),
    path('cajas/<int:pk>/edit', CajaEdit.as_view(), name='caja_edit'),

    path('cajas/bancos',BancoView.as_view(), name='banco_list'),
    path('cajas/bancos/create',BancoCreate.as_view(), name='banco_create'),
    path('cajas/bancos/<int:pk>/edit', BancoEdit.as_view(), name='banco_edit'),
    path('cajas/<int:id>/delete',banco_delete, name='banco_delete'),

    path('movimientos/list', CajaMovimientoList.as_view(), name='movimientos_list'),
    path('movimientos/create', CajaMovimientoCreate.as_view(), name='movimiento_create'),
    path('movimientos/<int:pk>/edit', CajaMovimientoEdit.as_view(), name='movimiento_edit'),
]

app/telas/urls.py
from django.urls import path
from .views import TelaInvoicePdfView, TelaList, TelaList, TelaCreate, TelaEdit, tela_delete,TelaOfertaView,TelaOfertaCreate, TelaOfertaInvoicePdfView,TelaOfertaUpdate, tela_oferta_delete

urlpatterns = [
    path('telas/',TelaList.as_view(), name='tela_list'),
    path('telas/create', TelaCreate.as_view(), name='tela_create'),
    path('telas/<int:pk>/edit', TelaEdit.as_view(), name='tela_edit'),
    path('telas/listado/pdf', TelaInvoicePdfView.as_view(), name='tela_listado_pdf'),
    path('telas/<int:id>/delete', tela_delete, name='tela_delete'),

    path('telas/oferta/',TelaOfertaView.as_view(), name='tela_oferta_list'),
    path('telas/oferta/create', TelaOfertaCreate.as_view(), name='tela_oferta_create'),
    path('telas/oferta/<int:pk>/edit/', TelaOfertaUpdate.as_view(), name='tela_oferta_edit'),
    path('telas/oferta/listado/pdf', TelaOfertaInvoicePdfView.as_view(), name='tela_oferta_listado_pdf'),
    path('telas/oferta/<int:id>/delete', tela_oferta_delete, name='tela_oferta_delete'),
    #path('telas/oferta/<int:pk>/edit', TelaOfertaEdit.as_view(), name='tela_oferta_edit'),
]

app/tipos/urls.py
from django.urls import path
from .views import CategoriaCreate, CategoriaView, CategoriaCreate, CategoriaEdit, categoria_delete, \
                    DisenhoCreate, DisenhoView, DisenhoCreate, DisenhoEdit, disenho_delete

urlpatterns = [
    #rutas para categoria
    path('categorias/',CategoriaView.as_view(), name='categoria_list'),
    path('categorias/create',CategoriaCreate.as_view(), name='categoria_create'),
    path('categorias/<int:pk>/edit', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/<int:id>/delete',categoria_delete, name='categoria_delete'),

    #rutas para disenho
    path('disenhos/',DisenhoView.as_view(), name='disenho_list'),
    path('disenhos/create',DisenhoCreate.as_view(), name='disenho_create'),
    path('disenhos/<int:pk>/edit', DisenhoEdit.as_view(), name='disenho_edit'),
    path('disenhos/<int:id>/delete',disenho_delete, name='disenho_delete'),
]

app/user/urls.py
from django.urls import path
from user.views import *

app_name = 'user'

urlpatterns = [
    # user
    path('users/', UserListView.as_view(), name='user_list'),
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='user_edit'),
    path('users/<int:id>/delete/',user_delete, name='user_delete'),
    
    # rol
    path('users/roles/', RolListView.as_view(), name='rol_list'),
    path('users/roles/create', RolCreateView.as_view(), name='rol_create'),
    path('users/roles/<int:pk>/edit', RolEditView.as_view(), name='rol_edit'),
    path('users/roles/<int:id>/delete', rol_delete, name='rol_delete'),
]

app/templates/base/partials/content.html
<div class="content">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        {% block content %}
        
        {% endblock %}
    </div>
</div>

app/templates/base/partials/form_error.html
<script type=text/javascript>
    toastr.options = {
        "progressBar": true,
        "timeOut": "6000",
        "extendedTimeOut": "2000",
    }

    {% if form.errors %}
        console.log('{{form.errors}}')
        {% for field in form %}
            {% for error in field.errors %}
                toastr.error('{{ error }}','Error')
            {% endfor %}
        {% endfor %}
    {% endif %}

</script>

app/templates/base/partials/functions_cuota.html
<script>
    function alert(title, content, callback, cancel) {
        $.confirm({
            theme: 'material',
            title: title,
            icon: 'fa fa-info',
            content: content,
            columnClass: 'small',
            typeAnimated: true,
            cancelButtonClass: 'btn-primary',
            draggable: true,
            dragWindowBorder: false,
            buttons: {
                info: {
                    text: "OK",
                    btnClass: 'btn-primary',
                    action: function () {
                        callback();
                    }
                },
            }
        })
    }
</script>

app/templates/base/partials/messages.html
<script type=text/javascript>
    toastr.options = {
        "progressBar": true,
        "timeOut": "6000",
        "extendedTimeOut": "2000",
    }

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                toastr.{{ message.tags }}('{{ message }}','Mensaje')
            {% elif message.tags == 'info' %}
                toastr.{{ message.tags }}('{{ message }}','Mensaje')
            {% elif message.tags == 'warning' %}
                toastr.{{ message.tags }}('{{ message }}','Mensaje')
            {% elif message.tags == 'error' %}
                toastr.{{ message.tags }}('{{ message }}','Mensaje')
            {% endif %}
        {% endfor %}
    {% endif %}

</script>

app/templates/base/partials/navbar.html
{% load static %}
    
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a href="/logout" class="nav-link">
                <i class="fas fa-sign-out-alt"></i> Salir
            </a>
        </li>
    </ul>
</nav>

<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <img src="{% static 'base/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">2M Textil</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'base/img/user.png' %}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.first_name }}  {{ request.user.last_name }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column nav-child-indent" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="{% url 'dashboard:dashboard' %}" class="nav-link">
                    <i class="nav-icon fas fa-chart-line"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-map-marked"></i>
                        <p> Ubicaciones <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'ubicaciones:departamento_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Departamentos</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'ubicaciones:ciudad_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Ciudades</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{% url 'clientes:cliente_list' %}" class="nav-link">
                    <i class="nav-icon far fa-id-card"></i>
                        <p>Clientes</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'proveedores:proveedor_list' %}" class="nav-link">
                    <i class="fas fa-dolly"></i>
                        <p>Proveedores</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-shopping-bag"></i>
                        <p> Compras <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href=" {% url 'compras:orden_compras_list' %}" class="nav-link">
                                <i class="fas fa-store-alt"></i>
                                <p>Orden de Compras</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'compras:compras_list' %}" class="nav-link">
                                <i class="fas fa-shopping-basket"></i>
                                <p>Compras</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'compras:compras_pago_list' %}" class="nav-link">
                                <i class="fab fa-cc-amazon-pay"></i>
                                <p>Deudas a Pagar</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p> Ventas <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'ventas:ventas_list' %}" class="nav-link">
                                <i class="fas fa-shopping-cart"></i>
                                <p>Ventas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'ventas:ventas_cobro_list' %}" class="nav-link">
                                <i class="fas fa-money-bill-wave"></i>
                                <p>Deudas a Cobrar</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p> Mercaderias <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'telas:tela_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Telas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'telas:tela_oferta_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Telas en Oferta</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'tipos:categoria_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Categorias</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'tipos:disenho_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Diseños</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cash-register"></i>
                        <p> Caja <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'cajas:caja_list' %}" class="nav-link">
                                <i class="fas fa-cash-register"></i>
                                <p>Apertura Caja</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'cajas:banco_list' %}" class="nav-link">
                                <i class="fas fa-landmark"></i>
                                <p>Registrar Banco</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'cajas:movimientos_list' %}" class="nav-link">
                                <i class="fas fa-hand-holding-usd"></i>
                                <p>Registrar Movimiento</p>
                            </a>
                        </li>
                    </ul>
                </li>
                
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-clipboard-list"></i>
                        <p> Inventario <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'inventario:inventario_list' %}" class="nav-link">
                                <i class="fas fa-clipboard-list"></i>
                                <p>Realizar Inventario</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p> Usuarios <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'user:user_list' %}" class="nav-link">
                                <i class="fas fa-users"></i>
                                <p>Usuarios</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'user:rol_list' %}" class="nav-link">
                                <i class="fas fa-clipboard"></i>
                                <p>Roles</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-box"></i>
                        <p> Configuraciones <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'configuracion:configuracion_usuario_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Metraje Minimo</p>
                            </a>
                        </li>
                    </ul>
                    <!--<ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'configuracion:configuracion_producto_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>IVA's</p>
                            </a>
                        </li>
                    </ul>-->
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'configuracion:configuracion_venta_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Timbrado</p>
                            </a>
                        </li>
                    </ul>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'configuracion:configuracion_egreso_list' %}" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Egreso Máximo</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

app/templates/base/partials/sweet_delete.html
<script>
    function eliminar (url, redirect_url) { 
        Swal.fire({
            "title":"¿Estás seguro que quiere eliminar?",
            "text":"Esta acción no se puede deshacer.",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545",
            "showLoaderOnConfirm": true,
            "preConfirm": function(login)  {
                return $.get(url,function(result) {
                    return result;
                })
                .fail(function(error) {
                    Swal.fire({
                        title:'Error',
                        text:'Ha Ocurrido un error, intente mas tarde',
                        icon:'error',
                        confirmButtonColor: '#007bff',
                    });
                })
            }
        })
        .then(function(result) {
            if(result.value) {
                if (result.value.error) {
                    Swal.fire({
                        title:'Error',
                        text:result.value.message,
                        icon:'error',
                        confirmButtonColor: '#007bff',
                    });
                }else{
                    Swal.fire({
                        title: 'Éxito',
                        text: result.value.message,
                        icon: 'success',
                        confirmButtonColor: '#007bff',
                        showCancelButton: false,
                        allowOutsideClick: false
                    }).then(function(result)  {
                        console.log(result);
                        window.location.href = redirect_url;
                    });

                }
            }
        });
    }
</script>